services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: authorization
      POSTGRES_USER: authorization
      POSTGRES_PASSWORD: authorization
    ports:
      - "5432"
  redis:
    image: redis:7-alpine
    ports:
      - "6379"
  risk-engine:
    image: wiremock/wiremock:3.13.2
    volumes:
      - ./local/risk-engine:/home/wiremock
    ports:
      - "8081:8080"
