spring:
  application:
    name: card-authorization-service
  jpa:
    open-in-view: false
  http:
    clients:
      imperative:
        factory: http-components
      connect-timeout: 100ms
      read-timeout: 150ms

logging:
  structured:
    format:
      console: ecs
