spring:
  application:
    name: card-authorization-service
  mvc:
    problemdetails:
      enabled: true
  http:
    clients:
      imperative:
        factory: http-components
      connect-timeout: 100ms
      read-timeout: 150ms

authorization:
  max-acceptable-risk-score: 70
  hold-validity: 7d

cache:
  cards:
    time-to-live: 10m

risk:
  scoring:
    base-url: http://localhost:8081

logging:
  structured:
    format:
      console: ecs
